In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [5]:
# Load dataset
df = pd.read_csv("vic_electricity.csv")

# View first rows
df.head()

,Time,Demand,Temperature,Date,Holiday
0,2011-12-31T13:00:00Z,4382.825174,21.40,2012-01-01,True
1,2011-12-31T13:30:00Z,4263.365526,21.05,2012-01-01,True
2,2011-12-31T14:00:00Z,4048.966046,20.70,2012-01-01,True
3,2011-12-31T14:30:00Z,3877.563330,20.55,2012-01-01,True
4,2011-12-31T15:00:00Z,4036.229746,20.40,2012-01-01,True


In [6]:
# Dataset info
df.info()

# Summary statistics
df.describe()

# Check missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 52608 entries, 0 to 52607
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Time         52608 non-null  str    
 1   Demand       52608 non-null  float64
 2   Temperature  52608 non-null  float64
 3   Date         52608 non-null  str    
 4   Holiday      52608 non-null  bool   
dtypes: bool(1), float64(2), str(2)
memory usage: 3.2 MB


Time           0
Demand         0
Temperature    0
Date           0
Holiday        0
dtype: int64

In [7]:
# Drop missing values if present
df = df.dropna()

In [9]:
print(df.columns.tolist())

['Time', 'Demand', 'Temperature', 'Date', 'Holiday']


In [13]:
df.columns = df.columns.str.strip()

In [15]:
print(df.head())
print(df.columns)

                   Time       Demand  Temperature        Date  Holiday
0  2011-12-31T13:00:00Z  4382.825174        21.40  2012-01-01     True
1  2011-12-31T13:30:00Z  4263.365526        21.05  2012-01-01     True
2  2011-12-31T14:00:00Z  4048.966046        20.70  2012-01-01     True
3  2011-12-31T14:30:00Z  3877.563330        20.55  2012-01-01     True
4  2011-12-31T15:00:00Z  4036.229746        20.40  2012-01-01     True
Index(['Time', 'Demand', 'Temperature', 'Date', 'Holiday'], dtype='str')


In [17]:
df.columns = df.columns.str.strip().str.lower()
print(df.columns)

Index(['time', 'demand', 'temperature', 'date', 'holiday'], dtype='str')


In [19]:
if 'high_demand' not in df.columns:
    print("Column missing!")

Column missing!


In [20]:
print(df.columns)

Index(['time', 'demand', 'temperature', 'date', 'holiday'], dtype='str')


In [28]:
print(df.columns)

Index(['Time', 'Demand', 'Temperature', 'Date', 'Holiday'], dtype='str')


In [32]:
print(df.head())
print(df.columns)

                   Time       Demand  Temperature        Date  Holiday
0  2011-12-31T13:00:00Z  4382.825174        21.40  2012-01-01     True
1  2011-12-31T13:30:00Z  4263.365526        21.05  2012-01-01     True
2  2011-12-31T14:00:00Z  4048.966046        20.70  2012-01-01     True
3  2011-12-31T14:30:00Z  3877.563330        20.55  2012-01-01     True
4  2011-12-31T15:00:00Z  4036.229746        20.40  2012-01-01     True
Index(['Time', 'Demand', 'Temperature', 'Date', 'Holiday'], dtype='str')


In [34]:
# 1. Import libraries
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier  # example model
from sklearn.datasets import load_iris  # example dataset

# 2. Load dataset (replace this with your own data if needed)
data = load_iris()
X = data.data
y = data.target

# 3. Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Train the model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# 5. Make predictions
y_pred = model.predict(X_test)

# 6. Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [37]:
print(df.columns.tolist())

['Time', 'Demand', 'Temperature', 'Date', 'Holiday']
